Assignments Machine learning
- Sophie
- Emmelien
- Isabelle
- Daan

In [2]:
# Loading the data

import os
import pandas as pd
import glob



def find(name, path):
    for root, dirs, files in os.walk(path):
        if name in files:
            return os.path.join(root, name)
path = os.path.dirname(os.path.abspath("ml_final"))
path_data = find("empdata.csv", path)
data = pd.read_csv(path_data)
        
col_headers = list(data.columns.values)
# print (col_headers)



In [5]:
# Missing values and imputing
print(data.isnull().any())
print(data.isnull().sum().sum())

Age                         False
Attrition                   False
BusinessTravel              False
DailyRate                   False
Department                  False
DistanceFromHome            False
Education                   False
EducationField              False
EmployeeCount               False
EmployeeNumber              False
EnvironmentSatisfaction     False
Gender                      False
HourlyRate                  False
JobInvolvement              False
JobLevel                    False
JobRole                     False
JobSatisfaction             False
MaritalStatus               False
MonthlyIncome               False
MonthlyRate                 False
NumCompaniesWorked          False
Over18                      False
OverTime                    False
PercentSalaryHike           False
PerformanceRating           False
RelationshipSatisfaction    False
StandardHours               False
StockOptionLevel            False
TotalWorkingYears           False
TrainingTimesL

No missing values 

In [ ]:
# resizing the dataset
# Todo
# - 

In [49]:
# splitting the data
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedShuffleSplit
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import scale, StandardScaler
from imblearn.under_sampling import RandomUnderSampler
from sklearn import preprocessing


le = preprocessing.LabelEncoder()
atrittion = data.iloc[:,1:2]
variables_ex_age = data.loc[:,list(data.columns[2:])]
age = data.iloc[:, 0:1]
atrittion12 = data.iloc[:,1:2]
x = le.fit(atrittion12).transform(atrittion12)



list_strings = ["BusinessTravel", "Department", "EducationField", "Gender", "JobRole", "MaritalStatus",  "OverTime"]

all_vars = pd.concat([age, variables_ex_age], axis=1)
# over 18 has one value so drop
all_varsnew = all_vars.drop(["Over18"], axis = 1)





dicci ={}
dicci2 ={}
lissa = []
le = preprocessing.LabelEncoder()
atrittion1 = le.fit(atrittion["Attrition"])
atrittion2 = le.transform(atrittion["Attrition"])
print (atrittion2)
for names in list_strings:
    dicci[names]= le.fit(all_varsnew[names])
    
    print(list(le.classes_))
    dicci2[names] = le.transform(all_varsnew[names])
    lissa.append(dicci2[names])

no_cat_vars = all_varsnew.drop(all_vars1.ix[:,list_strings].head(0).columns, axis=1)  
  
cat_vars = pd.DataFrame.from_dict(dicci2)

all_vars_pp = pd.concat([no_cat_vars,cat_vars], axis = 1)
print (dicci)
print (dicci2)
print(all_vars_pp.isnull().any())
print(all_vars_pp.isnull().sum().sum())


[1 0 1 ... 0 0 0]
['Non-Travel', 'Travel_Frequently', 'Travel_Rarely']
['Human Resources', 'Research & Development', 'Sales']
['Human Resources', 'Life Sciences', 'Marketing', 'Medical', 'Other', 'Technical Degree']
['Female', 'Male']
['Healthcare Representative', 'Human Resources', 'Laboratory Technician', 'Manager', 'Manufacturing Director', 'Research Director', 'Research Scientist', 'Sales Executive', 'Sales Representative']
['Divorced', 'Married', 'Single']
['No', 'Yes']
{'BusinessTravel': LabelEncoder(), 'Department': LabelEncoder(), 'EducationField': LabelEncoder(), 'Gender': LabelEncoder(), 'JobRole': LabelEncoder(), 'MaritalStatus': LabelEncoder(), 'OverTime': LabelEncoder()}
{'BusinessTravel': array([2, 1, 2, ..., 2, 1, 2]), 'Department': array([2, 1, 1, ..., 1, 2, 1]), 'EducationField': array([1, 1, 4, ..., 1, 3, 3]), 'Gender': array([0, 1, 1, ..., 1, 1, 1]), 'JobRole': array([7, 6, 2, ..., 4, 7, 2]), 'MaritalStatus': array([2, 1, 2, ..., 1, 1, 1]), 'OverTime': array([1, 0, 1

C:\Users\daan_\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\daan_\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\daan_\Anaconda3\lib\site-packages\ipykernel_launcher.py:44: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\Users\daan_\Anaconda3\lib\site-packages\pandas\core\indexing.py:116: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in th

In [50]:
X, y = all_vars_pp, atrittion2
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

print (y_train)

[0 0 1 ... 0 0 0]


In [51]:
# Feature selection
# Undersampeling

rus = RandomUnderSampler(replacement=False)


X_train_subsample, y_train_subsample = rus.fit_sample(X_train, y_train)
print(X_train.shape)
print(X_train_subsample.shape)
print(np.bincount(y_train_subsample))


(1102, 33)
(338, 33)
[169 169]


NameError: name 'LogisticRegressionCV' is not defined

In [56]:
# Scaling

from sklearn.preprocessing import StandardScaler, MinMaxScaler,MaxAbsScaler, RobustScaler


scaler1 = StandardScaler()
scaler = MinMaxScaler()
scaler3 = MaxAbsScaler()
scaler2 = RobustScaler()
X_train_scaled1 = scaler1.fit_transform(X_train)
X_train_scaled2 = scaler2.fit_transform(X_train)
X_train_scaled3 = scaler3.fit_transform(X_train)
X_train_scaled = scaler.fit_transform(X_train)
# y_train_scaled = scaler.fit_transform(y_train)

scale_list = []
scale_list.append(X_train_scaled)
scale_list.append(X_train_scaled1)
scale_list.append(X_train_scaled2)
scale_list.append(X_train_scaled3)

C:\Users\daan_\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\daan_\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\daan_\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [53]:
# feature selection

from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

# create ranking among all features by selecting only one
rfe = RFE(LinearRegression(), n_features_to_select=1)

rfe.fit(X_train, y_train)
rfe.ranking_

array([25, 28, 22, 13, 32, 29,  6, 27,  3,  4,  7, 30, 31, 11, 18, 15,  9,
       33, 10, 19, 14, 12, 21, 20, 17, 16, 26,  5, 23,  8, 24,  2,  1])

In [ ]:
# train set val set 


In [ ]:
# 